version: "3.9"

volumes:
  mysql-data:

services:
  ##### node api #####
  node:
    image: node:lts-alpine
    working_dir: /usr/src/node
    restart: always
    environment:
      SERVER_NAME: "${PROJECT_NAME}"
      SERVER_HOST: "localhost"
      SERVER_PORT: "${NODE_PORT}"
      TYPEORM_CONNECTION: "mysql"
      TYPEORM_HOST: "${HOST_NAME}"
      TYPEORM_PORT: "${DATABASE_PORT}"
      TEST_DATABASE: "${TEST_DATABASE}"
      COMMUNICATION_DATABASE: "${DATABASE_NAME}"
      TYPEORM_DATABASE: "${DATABASE_NAME}"
      TYPEORM_USERNAME: "root"
      TYPEORM_PASSWORD: "${DATABASE_PASSWORD}"
      TYPEORM_ENTITIES: "build/src/entity/**/*.js"
      TYPEORM_ENTITIES_DIR: "src/entity"
      TYPEORM_MIGRATIONS_DIR: "src/migrations"
      TYPEORM_SYNCHRONIZE: "true"
      TYPEORM_LOGGING: "false"
      NODE_ENV: "development"
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./src/:/usr/src/node/src/
      - ./tests/:/usr/src/node/tests/
      - ./package.json:/usr/src/node/package.json
      - ./package-lock.json:/usr/src/node/package-lock.json
      - ./tsconfig.json:/usr/src/node/tsconfig.json
      - ./node_modules/:/usr/src/node/node_modules/
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    networks:
      - communication_net

  ##### mysql #####
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "${DATABASE_NAME}"
      MYSQL_USER: "${DATABASE_USER}"
      MYSQL_PASSWORD: "${DATABASE_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
    command: sh -c "
        echo 'CREATE DATABASE IF NOT EXISTS ${DATABASE_NAME}; CREATE DATABASE IF NOT EXISTS ${TEST_DATABASE};' > /docker-entrypoint-initdb.d/init.sql;
        /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "${DATABASE_PORT}:3306"
    networks:
      - communication_net

networks:
  communication_net:
    driver: bridge
    ipam:
      config:
        - subnet: "${HOST_NAME}/24"